/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Simple health check
         * @description Returns a simple message to verify the API is running
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API is running successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detailed health check
         * @description Returns liveness and readiness information.
         *     **Liveness** (200 vs 503) is determined by DB reachability alone.
         *     **Indexer lag** is reported in the body for observability but only
         *     forces a 503 when the indexer is actually enabled
         *     (`STREAM_CONTRACT_ID` env var set) and its state row is stale
         *     (lag > 60 s). A cold-started instance with no state row yet, or a
         *     deployment with the indexer intentionally disabled, always returns 200
         *     as long as the DB is reachable.
         *     **Event-processing failures** are also reported. When the indexer is
         *     enabled and recent per-event failures spike (≥50% of attempts in the
         *     last 5 minutes, with ≥3 samples), the endpoint returns 503 even if
         *     lag looks healthy (the IndexerState upsert bumps updatedAt every poll).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
                /** @description Service is degraded or unhealthy */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all webhooks for authenticated user */
        get: {
            parameters: {
                query: {
                    userAddress: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of webhook subscriptions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            subscriptions?: components["schemas"]["WebhookSubscription"][];
                        };
                    };
                };
                /** @description Missing userAddress */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Register a new webhook subscription
         * @description Creates a webhook subscription. The returned `secretKey` is only shown once.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Stellar public key */
                        userAddress: string;
                        /** Format: uri */
                        targetUrl: string;
                        eventTypes: ("CREATED" | "TOPPED_UP" | "WITHDRAWN" | "CANCELLED" | "COMPLETED" | "PAUSED" | "RESUMED" | "FEE_COLLECTED")[];
                    };
                };
            };
            responses: {
                /** @description Webhook created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            subscription?: components["schemas"]["WebhookSubscription"];
                            /** @description Webhook signing secret (returned only once) */
                            secretKey?: string;
                            message?: string;
                        };
                    };
                };
                /** @description Missing required fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a webhook subscription */
        delete: {
            parameters: {
                query: {
                    userAddress: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Webhook deleted successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid id or missing userAddress */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a test ping to a webhook */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        userAddress: string;
                    };
                };
            };
            responses: {
                /** @description Test webhook sent */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Test webhook sent */
                            message?: string;
                            result?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description Missing id or userAddress */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a wallet public key
         * @description Registers a new Stellar wallet public key or returns the existing user if already registered.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Stellar public key (G...)
                         * @example GABC123XYZ456DEF789GHI012JKL345MNO678PQR901STU234VWX567YZA
                         */
                        publicKey: string;
                    };
                };
            };
            responses: {
                /** @description User already exists */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description User registered successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Invalid request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{publicKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a user by public key
         * @description Returns user details along with recent sent and received streams.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Stellar public key */
                    publicKey: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current authenticated user
         * @description Returns the currently authenticated user's details (protected endpoint)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Unauthorized - invalid or missing token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{address}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get aggregate stream summary for a user
         * @description Returns dashboard/profile summary data for a wallet address:
         *     total created streams, total streamed out/in, current claimable across
         *     active incoming streams, and active stream counts.
         *
         *     Response is cached for 30 seconds to reduce DB load.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Stellar public key address */
                    address: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User stream summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserStreamSummary"];
                    };
                };
                /** @description Address is required */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{publicKey}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch user activity history
         * @description Returns a paginated chronological history of all stream events associated with the user.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of events to return */
                    limit?: number;
                    /** @description Number of events to skip for pagination */
                    offset?: number;
                };
                header?: never;
                path: {
                    /** @description Stellar public key */
                    publicKey: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of user events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserEventListResponse"];
                    };
                };
                /** @description Invalid pagination parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{address}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export transaction history for tax and accounting
         * @description Generates CSV or JSON export of stream transactions for QuickBooks, Xero, CoinTracker, etc.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Export format */
                    format?: "csv" | "json";
                    /** @description Filter by transaction direction */
                    direction?: "incoming" | "outgoing" | "all";
                    /** @description Start date (ISO 8601 or Unix timestamp) */
                    startDate?: string;
                    /** @description End date (ISO 8601 or Unix timestamp) */
                    endDate?: string;
                    /** @description Filter by specific token contract */
                    tokenAddress?: string;
                };
                header?: never;
                path: {
                    /** @description Stellar public key */
                    address: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Transaction export file */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Invalid parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/streams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List payment streams
         * @description Retrieve a list of payment streams with optional filtering, sorting, and pagination.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by sender public key */
                    sender?: string;
                    /** @description Filter by recipient public key */
                    recipient?: string;
                    /** @description Filter by stream status */
                    status?: "active" | "cancelled" | "completed" | "paused";
                    /** @description Filter by token contract address */
                    token?: string;
                    /** @description Sort field */
                    sort?: "createdAt" | "startTime" | "lastUpdateTime" | "depositedAmount" | "endTime";
                    /** @description Sort order */
                    order?: "asc" | "desc";
                    /** @description Max results per page (capped at 100) */
                    limit?: number;
                    /** @description Number of results to skip */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of streams */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StreamListResponse"];
                    };
                };
                /** @description Invalid status or pagination parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a new payment stream
         * @description Creates or reactivates a payment stream record for the authenticated wallet. The authenticated wallet must be the stream sender.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description On-chain stream ID
                         * @example 1
                         */
                        streamId: number;
                        /**
                         * @description Sender Stellar public key — must match the authenticated wallet
                         * @example GABC123XYZ456DEF789GHI012JKL345MNO678PQR901STU234VWX567YZA
                         */
                        sender: string;
                        /**
                         * @description Recipient Stellar public key
                         * @example GDEF456ABC789GHI012JKL345MNO678PQR901STU234VWX567YZA123BCD
                         */
                        recipient: string;
                        /**
                         * @description Token contract address
                         * @example CBCD789EFG012HIJ345KLM678NOP901QRS234TUV567WXY890ZAB123CDE
                         */
                        tokenAddress: string;
                        /**
                         * @description Payment rate per second (i128 as string)
                         * @example 100
                         */
                        ratePerSecond: string;
                        /**
                         * @description Total deposited amount (i128 as string)
                         * @example 10000
                         */
                        depositedAmount: string;
                        /**
                         * @description Stream start time (Unix timestamp)
                         * @example 1708531200
                         */
                        startTime: number;
                    };
                };
            };
            responses: {
                /** @description Stream created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Stream"];
                    };
                };
                /** @description Invalid input data */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized - missing or invalid authentication token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - sender does not match the authenticated wallet, or stream is owned by another wallet */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Too Many Requests - rate limit exceeded (10 requests per minute) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/streams/summary/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user stream summary
         * @description Aggregate dashboard/profile summary for a wallet address. Cached for 30 seconds.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Stellar public key */
                    address: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User stream summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserStreamSummary"];
                    };
                };
                /** @description Address is required */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/streams/{streamId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get stream details
         * @description Returns a single stream. Falls back to live on-chain data when the DB record is missing or stale.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description On-chain stream ID */
                    streamId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Stream details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Stream"];
                    };
                };
                /** @description Invalid streamId parameter */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Stream not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/streams/{streamId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get stream events
         * @description Retrieve events for a specific stream with pagination, filtering, and sorting.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Number of events to return per page (default: 50, max: 200) */
                    limit?: number;
                    /** @description Number of events to skip (default: 0) */
                    offset?: number;
                    /** @description Filter events by type */
                    eventType?: "CREATED" | "TOPPED_UP" | "WITHDRAWN" | "CANCELLED" | "COMPLETED" | "PAUSED" | "RESUMED" | "FEE_COLLECTED" | "FEE_CONFIG_UPDATED" | "ADMIN_TRANSFERRED";
                    /** @description 1-based page index (offset based). Ignored when `cursor` is set. */
                    page?: number;
                    /** @description Event id cursor for stable pagination (hasMore-aware). Ignored when `offset` is set. */
                    cursor?: string;
                    /** @description Sort order by timestamp (default: desc) */
                    order?: "asc" | "desc";
                };
                header?: never;
                path: {
                    /** @description On-chain stream ID */
                    streamId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated stream events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StreamEventListResponse"];
                    };
                };
                /** @description Invalid request parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Stream not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/streams/{streamId}/claimable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get actionable claimable amount for a stream
         * @description Returns the amount claimable right now (or at an optional timestamp). Uses a 5s-cached computation, with an on-chain fallback when the record is missing or stale.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Optional Unix timestamp (seconds) to compute the claimable amount at */
                    at?: number;
                };
                header?: never;
                path: {
                    /** @description On-chain stream ID */
                    streamId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Claimable amount */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClaimableResponse"];
                    };
                };
                /** @description Invalid streamId or `at` parameter */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Stream not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/streams/{streamId}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause a payment stream
         * @description Pause an active stream. Only the sender can pause their own stream.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description On-chain stream ID */
                    streamId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Stream paused successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PauseResumeResponse"];
                    };
                };
                /** @description Invalid streamId, or on-chain pause simulation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized - missing or invalid authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - caller is not the stream sender */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Stream not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Conflict - stream already paused or inactive */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/streams/{streamId}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume a paused payment stream
         * @description Resume a paused stream. Only the sender can resume their own stream.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description On-chain stream ID */
                    streamId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Stream resumed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PauseResumeResponse"];
                    };
                };
                /** @description Invalid streamId, or on-chain resume simulation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized - missing or invalid authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - caller is not the stream sender */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Stream not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Conflict - stream not paused or inactive */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/streams/{streamId}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Withdraw claimable balance from a payment stream
         * @description Withdraws the currently claimable amount. Only the recipient can withdraw.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description On-chain stream ID */
                    streamId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Withdrawal submitted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WithdrawResponse"];
                    };
                };
                /** @description Invalid streamId or contract revert */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized - missing or invalid authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - caller is not the stream recipient */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Stream not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Conflict - no claimable balance available */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/streams/{streamId}/top-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Top up a payment stream
         * @description Adds additional funds to an existing active stream. Only the original sender can top up.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description On-chain stream ID */
                    streamId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Amount to add to the stream deposit (i128 as string)
                         * @example 5000
                         */
                        amount: string;
                    };
                };
            };
            responses: {
                /** @description Stream topped up successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TopUpResponse"];
                    };
                };
                /** @description Invalid request — amount missing or not a positive integer string */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized - missing or invalid authentication token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - caller is not the stream sender */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Stream not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Conflict - stream inactive or paused */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/streams/{streamId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel an active payment stream
         * @description Cancels an active payment stream on the Stellar network.
         *     Only the original sender can cancel the stream.
         *     Accrued tokens are sent to the recipient, and the remainder is refunded to the sender.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description On-chain stream ID */
                    streamId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Stream cancelled successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CancelResponse"];
                    };
                };
                /** @description Invalid streamId or transaction simulation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized - missing or invalid authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - only sender can cancel */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Stream not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Stream already cancelled or completed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List stream events for a wallet (paginated, filterable)
         * @description Returns a reverse-chronological list of stream events where the wallet
         *     was either the sender or recipient. Supports event-type filtering and
         *     limit/offset pagination — used by the frontend activity timeline.
         */
        get: {
            parameters: {
                query: {
                    /** @description Stellar public key (G...) */
                    address: string;
                    /**
                     * @description Comma-separated list of event types to include. Allowed values:
                     *     CREATED, TOPPED_UP, WITHDRAWN, CANCELLED, COMPLETED, PAUSED,
                     *     RESUMED, FEE_COLLECTED, FEE_CONFIG_UPDATED, ADMIN_TRANSFERRED.
                     */
                    type?: string;
                    limit?: number;
                    offset?: number;
                    /** @description Optional 1-based page index. Ignored when offset is set. */
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated event list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventListResponse"];
                    };
                };
                /** @description Missing/invalid `address` or invalid `type` filter */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized - missing or invalid authentication token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - `address` must match the authenticated wallet */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Subscribe to real-time stream events
         * @description Establishes a Server-Sent Events (SSE) connection for real-time updates.
         *
         *     **Reconnection Strategy:**
         *     - Browser automatically reconnects with exponential backoff
         *     - Initial retry: 1s, max: 30s
         *     - Client should implement custom reconnection logic for production
         *
         *     **Event Types:**
         *     - `stream.created` - New stream created
         *     - `stream.topped_up` - Stream received additional funds
         *     - `stream.withdrawn` - Funds withdrawn from stream
         *     - `stream.cancelled` - Stream cancelled
         *     - `stream.completed` - Stream completed
         *
         *     **Sandbox Mode:**
         *     - Add header `X-Sandbox-Mode: true` or query parameter `?sandbox=true`
         *     - Sandbox events are clearly marked with `_sandbox` metadata
         *     - Sandbox events are isolated from production events
         */
        get: {
            parameters: {
                query?: {
                    /** @description Enable sandbox mode via query parameter */
                    sandbox?: "true" | "1";
                    /**
                     * @description Array of stream IDs to subscribe to
                     * @example [
                     *       "1",
                     *       "2"
                     *     ]
                     */
                    streams?: string[];
                    /**
                     * @description Array of user public keys to subscribe to
                     * @example [
                     *       "GABC...",
                     *       "GDEF..."
                     *     ]
                     */
                    users?: string[];
                    /**
                     * @description Subscribe to all events
                     * @example false
                     */
                    all?: boolean;
                };
                header?: {
                    /** @description Enable sandbox mode for testing */
                    "X-Sandbox-Mode"?: "true" | "1";
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SSE connection established. Events are emitted as `data:` frames of type stream.created, stream.topped_up, stream.withdrawn, stream.cancelled, stream.completed, stream.paused, stream.resumed, fee.collected. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                /** @description Invalid subscription parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized - missing or invalid authentication token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get SSE connection statistics
         * @description Returns current SSE connection metrics for monitoring (admin only)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Connection statistics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SseStats"];
                    };
                };
                /** @description Unauthorized - missing or invalid authentication token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - admin access required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a sign challenge for wallet authentication */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example GABC... */
                        publicKey: string;
                    };
                };
            };
            responses: {
                /** @description Challenge nonce issued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthChallengeResponse"];
                    };
                };
                /** @description Invalid publicKey */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Too many requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify signed challenge and receive JWT */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        publicKey: string;
                        /** @description Base64-encoded XDR signed transaction containing the nonce */
                        signedTransaction: string;
                    };
                };
            };
            responses: {
                /** @description JWT token */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthVerifyResponse"];
                    };
                };
                /** @description Missing publicKey or signedTransaction */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Invalid signature or expired challenge */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Too many requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Protocol health metrics */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Protocol health metrics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            total_streams?: number;
                            active_streams?: number;
                            paused_streams?: number;
                            completed_streams?: number;
                            cancelled_streams?: number;
                            /** @description Sum of withdrawn amounts (i128 as string) */
                            total_volume_streamed?: string;
                            streams?: {
                                active?: number;
                                paused?: number;
                                total?: number;
                                byStatus?: {
                                    [key: string]: number;
                                };
                            };
                            events?: {
                                last24h?: number;
                            };
                            fees?: {
                                totalFeesCollectedByToken?: {
                                    [key: string]: string;
                                };
                                feesLast24h?: {
                                    [key: string]: string;
                                };
                            };
                            sse?: {
                                activeConnections?: number;
                            };
                            indexer?: {
                                lastLedger?: number;
                                lagSeconds?: number | null;
                                /** Format: date-time */
                                lastUpdated?: string | null;
                                eventsProcessed?: number;
                                eventsFailed?: number;
                                lastErrorAt?: string | null;
                                degraded?: boolean;
                            };
                            cache?: {
                                [key: string]: unknown;
                            };
                            pgPool?: {
                                [key: string]: unknown;
                            };
                            uptime?: number;
                            /** Format: date-time */
                            timestamp?: string;
                            /** Format: date-time */
                            calculatedAt?: string;
                        };
                    };
                };
                /** @description Unauthorized - missing or invalid authentication token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - admin access required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/indexer/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get indexer status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Indexer status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Unauthorized - missing or invalid authentication token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - admin access required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/indexer/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset indexer lastProcessedLedger */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        ledger: number;
                    };
                };
            };
            responses: {
                /** @description Reset successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            ok?: boolean;
                            lastLedger?: number;
                        };
                    };
                };
                /** @description Invalid ledger value */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized - missing or invalid authentication token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - admin access required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/indexer/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replay events from a given ledger (StreamEvent rows deduplicated; stream mutations not idempotent — see indexerService.ts JSDoc) */
        post: {
            parameters: {
                query: {
                    from_ledger: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Replay started */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            ok?: boolean;
                            replayingFrom?: number;
                            requestId?: string;
                        };
                    };
                };
                /** @description Invalid from_ledger value */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized - missing or invalid authentication token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - admin access required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /**
             * Format: uuid
             * @description Unique identifier for the user
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * @description Stellar public key (G...)
             * @example GABC123XYZ456DEF789GHI012JKL345MNO678PQR901STU234VWX567YZA
             */
            publicKey: string;
            /**
             * Format: date-time
             * @description User creation timestamp
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            updatedAt?: string;
        };
        Stream: {
            /**
             * Format: uuid
             * @description Database UUID
             */
            id: string;
            /**
             * @description On-chain stream ID
             * @example 1
             */
            streamId: number;
            /**
             * @description Sender Stellar public key
             * @example GABC123XYZ456DEF789GHI012JKL345MNO678PQR901STU234VWX567YZA
             */
            sender: string;
            /**
             * @description Recipient Stellar public key
             * @example GDEF456ABC789GHI012JKL345MNO678PQR901STU234VWX567YZA123BCD
             */
            recipient: string;
            /**
             * @description Token contract address
             * @example CBCD789EFG012HIJ345KLM678NOP901QRS234TUV567WXY890ZAB123CDE
             */
            tokenAddress: string;
            /**
             * @description Payment rate per second (i128 as string)
             * @example 100
             */
            ratePerSecond: string;
            /**
             * @description Total deposited amount (i128 as string)
             * @example 10000
             */
            depositedAmount?: string;
            /**
             * @description Total withdrawn amount (i128 as string)
             * @example 2500
             */
            withdrawnAmount?: string;
            /**
             * @description Stream start time (Unix timestamp)
             * @example 1708531200
             */
            startTime?: number;
            /**
             * @description Last update time (Unix timestamp)
             * @example 1708534800
             */
            lastUpdateTime?: number;
            /**
             * @description Stream active status
             * @example true
             */
            isActive?: boolean;
            /**
             * @description Whether the stream is currently paused
             * @example false
             */
            isPaused?: boolean;
            /**
             * @description Ledger timestamp when the stream was last paused (Unix), null if not paused
             * @example null
             */
            pausedAt?: number | null;
            /**
             * @description Cumulative seconds the stream has spent paused
             * @example 0
             */
            totalPausedDuration?: number;
            /**
             * @description Ledger timestamp when the stream ended (Unix), null if still active
             * @example null
             */
            endTime?: number | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        StreamEvent: {
            /** Format: uuid */
            id: string;
            /** @description Reference to stream ID */
            streamId: number;
            /**
             * @description Type of stream event
             * @example TOPPED_UP
             * @enum {string}
             */
            eventType: "CREATED" | "TOPPED_UP" | "WITHDRAWN" | "CANCELLED" | "COMPLETED" | "PAUSED" | "RESUMED" | "FEE_COLLECTED";
            /**
             * @description Amount involved in event (i128 as string)
             * @example 5000
             */
            amount?: string | null;
            /**
             * @description Stellar transaction hash
             * @example a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6
             */
            transactionHash: string;
            /**
             * @description Ledger sequence number
             * @example 12345678
             */
            ledgerSequence: number;
            /**
             * @description Event timestamp (Unix)
             * @example 1708531200
             */
            timestamp: number;
            /** @description Additional event data (JSON string) */
            metadata?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        StreamListResponse: {
            /** @description Streams matching the filter, sorted and paginated */
            data: components["schemas"]["Stream"][];
            /** @description Total number of streams matching the filter */
            total: number;
            /** @description Whether more results are available past this page */
            hasMore: boolean;
            /** @description Page size applied (capped at MAX_STREAM_PAGE_SIZE) */
            limit: number;
            /** @description Number of results skipped */
            offset: number;
        };
        StreamEventListResponse: {
            /** @description Events for the stream, sorted by timestamp (tie-broken by id) */
            data: components["schemas"]["StreamEvent"][];
            /** @description Total number of events matching the filter */
            total: number;
            /** @description Whether more results are available past this page */
            hasMore: boolean;
        };
        EventListResponse: {
            /** @description Reverse-chronological stream events for the wallet */
            events: components["schemas"]["StreamEvent"][];
            /** @description Total number of matching events */
            total: number;
            /** @description Page size applied (capped at 200) */
            limit: number;
            /** @description Number of events skipped */
            offset: number;
            /** @description Whether more results are available past this page */
            hasMore: boolean;
        };
        UserEventListResponse: {
            /** @description Events associated with the user, newest first */
            data: components["schemas"]["StreamEvent"][];
            /** @description Total number of matching events */
            total: number;
            /** @description Whether more results are available past this page */
            hasMore: boolean;
            /** @description Page size applied (capped at 200) */
            limit: number;
            /** @description Number of events skipped */
            offset: number;
        };
        UserStreamSummary: {
            /** @description Stellar public key */
            address: string;
            /** @description Number of streams this wallet sent */
            totalStreamsCreated: number;
            /** @description Sum of withdrawn amounts on outgoing streams (i128 as string) */
            totalStreamedOut: string;
            /** @description Sum of withdrawn amounts on incoming streams (i128 as string) */
            totalStreamedIn: string;
            /** @description Total currently claimable across active incoming streams (i128 as string) */
            currentClaimable: string;
            activeOutgoingCount: number;
            activeIncomingCount: number;
            /**
             * @description True when the number of streams was capped at MAX_USER_STREAMS per direction
             * @example false
             */
            truncated?: boolean;
        };
        ClaimableResponse: {
            /** @description On-chain stream ID */
            streamId?: number;
            /** @description Payment rate per second (i128 as string) */
            ratePerSecond?: string;
            /** @description Total deposited amount (i128 as string) */
            depositedAmount?: string;
            /** @description Total withdrawn amount (i128 as string) */
            withdrawnAmount?: string;
            /** @description Stream start time (Unix timestamp) */
            startTime?: number;
            /** @description Last state update time (Unix timestamp) */
            lastUpdateTime?: number;
            /** @description Amount claimable at the requested time (i128 as string) */
            claimableAmount: string;
            /** @description Whether the claimable amount is positive */
            actionable: boolean;
            /** @description Unix timestamp of the calculation */
            calculatedAt: number;
            /** @description Whether the value came from cache or a fresh computation */
            cached?: boolean;
            /**
             * @description Where the value was computed from
             * @enum {string}
             */
            source?: "db" | "chain";
        };
        PauseResumeResponse: {
            /** @example true */
            success: boolean;
            streamId: number;
            /** @description Stellar transaction hash of the pause/resume simulation */
            txHash: string;
            stream?: components["schemas"]["Stream"];
        };
        TopUpResponse: {
            streamId: number;
            /** @description Stellar transaction hash */
            txHash: string;
            /** @description New total deposited amount after the top-up (i128 as string) */
            depositedAmount: string;
        };
        WithdrawResponse: {
            /** @example true */
            success: boolean;
            streamId: number;
            /** @description Stellar transaction hash of the withdrawal */
            txHash: string;
            /** @description Amount withdrawn (i128 as string) */
            amount: string;
            stream?: components["schemas"]["Stream"];
        };
        CancelResponse: {
            /** @description Stellar transaction hash of the cancel */
            txHash: string;
            /**
             * @example CANCELLED
             * @enum {string}
             */
            status: "CANCELLED";
        };
        AuthChallengeResponse: {
            /** @description Hex-encoded nonce to sign via a Stellar manage_data operation */
            nonce: string;
            /** @description Unix timestamp (ms) when the challenge expires (60s) */
            expiresAt: number;
        };
        AuthVerifyResponse: {
            /** @description JWT to use in the Authorization: Bearer header */
            token: string;
            /** @description Token lifetime in seconds (3600) */
            expiresIn: number;
        };
        SseStats: {
            /** @example 42 */
            activeConnections: number;
            /** @example 8 */
            activeIps: number;
            /** @example 5 */
            perIpPeakConnections: number;
            /** @example 10000 */
            maxConnections: number;
            /** Format: date-time */
            timestamp: string;
        };
        WebhookSubscription: {
            /** @description Webhook subscription id */
            id: string;
            /** @description Stellar public key the subscription belongs to */
            userAddress: string;
            /** @description HTTPS endpoint receiving the events */
            targetUrl: string;
            eventTypes: ("CREATED" | "TOPPED_UP" | "WITHDRAWN" | "CANCELLED" | "COMPLETED" | "PAUSED" | "RESUMED" | "FEE_COLLECTED")[];
            active: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        HealthResponse: {
            /**
             * @example ok
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * @example connected
             * @enum {string}
             */
            db: "connected" | "disconnected";
            /** @description Whether the event indexer is configured */
            indexerEnabled: boolean;
            /** @description Seconds since last indexer update, or null when no state row exists yet */
            indexerLag?: number | null;
            /** @description Lifetime count of successfully processed indexer events */
            eventsProcessed?: number;
            /** @description Lifetime count of indexer events that threw during processing */
            eventsFailed?: number;
            /**
             * Format: date-time
             * @description Most recent per-event processing failure
             */
            lastErrorAt?: string | null;
            /** @description True when recent event-processing failure rate spikes */
            indexerDegraded?: boolean;
            /** @description Server uptime in seconds */
            uptime: number;
            /** @description Per-subsystem status breakdown */
            checks: {
                database?: {
                    /** @enum {string} */
                    status?: "ok" | "down";
                };
                indexer?: {
                    /** @enum {string} */
                    status?: "ok" | "degraded" | "disabled";
                    enabled?: boolean;
                    lagSeconds?: number | null;
                };
                redis?: {
                    /** @enum {string} */
                    status?: "ok" | "unavailable" | "not_configured";
                };
                sorobanRpc?: {
                    /** @enum {string} */
                    status?: "ok" | "down";
                };
            };
        };
        Error: {
            /**
             * @description Error message
             * @example Resource not found
             */
            error?: string;
            /**
             * @description Error code
             * @example NOT_FOUND
             */
            code?: string;
            /** @description Human-readable detail (present on many error responses) */
            message?: string | null;
            /** @description Structured validation issues (zod) when the error is a 400 */
            details?: Record<string, never>[] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
